language: node_js
env:
  global:
    - NPM_CONFIG_LOGLEVEL=warn
    - secure: BOUcDlu1QI46TZPch8lGBsaNNhaYuWaxrAljM4QOxoC4hJSt52lw6U6x0fPfwmIAVUIrc145VJrwDFJbDVKJZ3cl+OUCVcmtS5oal0D/2erTzKhJcS75GiKs0EqN1LAgB1UvlAWNvc5TxvmzRFQ+aA26SCODsQ6d9FdB9xt9oVxQ9LdijQjynciZ2cI68MVNocihzTyOLHubUwOHZYKSeyHyxDsEGkLTEeJfl5iVckB6AZKttPknpdiHv0mcqSRDIxP+X6Gjv1XxlnYiTQiDMjXdFowpvXdFqivyW20maRy6MzvUjnhgNKNxgruIwGICmpPfMpQcXaGiV0XAkpdzL/bz5oftVzrINViuRBcBDvveEtdxObJ2oueW4qd53HdZjISXNPZQnJqn5iH4TRQRO2pdbxISu+hoEr2fbZdCR2pCl5oI2N4imOS4N6YCaLLRmp+o4K0iSxUnj14Ksn7b0zMZRbKLuWxHWD+pZRkoR9ySUjNYOlkHTKRy7cDSBsuBfblt/Ir3ixFRY8srpHUMPBsaR6Du9iigLmn9gChkH8RFVjvg+/0fFe5g57vbf4zdff1YdWX7mE9heCD2HjQk/asQQgDJwA+ZaiP0cvnLj+u1L5ISMFZfyOzdOuBpFpRXiAp2ntw07MUFLGyNbYntXR0+22H0LVhZ+2J8MpEZfU8=
before_install:
  - npm install -g greenkeeper-lockfile
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - npm test
after_script:
  - greenkeeper-lockfile-upload
cache:
  directories:
    - node_modules
# This causes builds for merges and direct pushes to master.
# Other branches are pull requests and build are triggered via the
# pull request hook
branches:
  only:
    - master
    - /^greenkeeper/.*$/
